### PR TITLE
Updated to API Version 24 & fix QT 5.10 build

### PR DESCRIPTION
**Pull request by frebib**

### CODE REVIEW

**Comment by DiscordIstFuerMichAbfall** [comment]
Cool, thanks!

**Comment by MGraefe** [comment]
Very nice, thanks!

**Comment by Bluscream** [comment]
@frebib could you do the same for pyTSon pleeease? <3

**Comment by frebib** [comment]
@Bluscream Sure, I can give it a go. By the looks of things, it has a lot more broken with it than just the Teamspeak API version being out of date. It straight up fails to build with python 3.8 that I have installed. No doubt PythonQt will be very broken too. This is the current state without me changing anything:
https://gist.github.com/frebib/a972507d9d7302ee88963e9176f4122f/raw

**Pull request merged**
