### PR TITLE
Added local volume slider

### PR DESCRIPTION
**Pull request by Bluscream**
To have different volumes for remote and local

grafik

### CODE REVIEW

**Comment by MGraefe** [comment]
Hi, thank you for your pull request. As far as I can see you didn't implement the actual functionality? I see only a .ui file change. Just the slider without functionality is useless.

**Comment by Bluscream** [comment]
I sadly am unable to do that, but the UI part is atleast some of the work, right?

**Comment by MGraefe** [comment]
I can't accept such an incomplete pull request.

**Comment by Bluscream** [comment]
See it as a feature request then

**Comment by Bluscream** [comment]
Or as a reminder of the request i did like 6 months ago

**Comment by Bluscream** [comment]
Any news for this?

**Pull request closed without merging**
